# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BcMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(default=datetime.datetime.now)),
                ('secretary', models.CharField(max_length=200)),
                ('guest_speaker', models.CharField(max_length=200)),
                ('minutes', models.TextField()),
                ('next_date', models.DateField(verbose_name='Next Meeting Date')),
                ('cost', models.IntegerField(verbose_name='Cost ($)')),
            ],
            options={
                'verbose_name': 'Business Club Meeting',
                'verbose_name_plural': 'Business Club Meetings',
            },
        ),
        migrations.CreateModel(
            name='BusinessClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('established', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('postal_address', models.CharField(blank=True, max_length=600, null=True)),
                ('physical_address', models.TextField(blank=True, max_length=600, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('established', models.IntegerField()),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('avatar', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=400, null=True)),
                ('account_no', models.CharField(blank=True, max_length=200, null=True)),
                ('forex_rate', models.IntegerField()),
                ('mm_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Money Number')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=400)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('t', 'Training'), ('v', 'Company Visit'), ('e', 'Exhibition')], default='t', max_length=1, null=True, verbose_name='Event Type')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Full Name')),
                ('join_date', models.DateField(default=datetime.datetime.now)),
                ('subscription_date', models.DateField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(max_length=200)),
                ('company_logo', models.CharField(blank=True, default='logos/logogeneric.png', max_length=200, null=True)),
                ('description', models.TextField(default='This is my company description')),
                ('website', models.URLField(blank=True, null=True)),
                ('sub_status', models.BooleanField(verbose_name='Subscription')),
                ('status', models.CharField(choices=[('10', 'Member'), ('1', 'Non-Member')], default=10, max_length=2, verbose_name='user status')),
                ('password', models.CharField(default='$2y$10$eM0VDmCiZq692kNgs4K5R.NFKFSQAkV0SkzAC7lW6Ib.iwy2LdvYu', max_length=200)),
                ('business_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.BusinessClub')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Member Interest',
                'verbose_name_plural': 'Member Interests',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100, verbose_name='partner')),
                ('contact', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
                ('speciality', models.ManyToManyField(to='secretariat.MemberInterest')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=300)),
                ('country_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Staffactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity_end', models.DateField()),
                ('activity', models.TextField()),
                ('location', models.CharField(max_length=400)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Staff')),
            ],
            options={
                'verbose_name': 'Staff Activities',
                'verbose_name_plural': 'Staff Activities',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.CharField(max_length=400)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter', verbose_name='Country')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, to='secretariat.MemberInterest'),
        ),
        migrations.AddField(
            model_name='member',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Sector'),
        ),
        migrations.AddField(
            model_name='member',
            name='sector_desk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secretariat.SectorDesk'),
        ),
        migrations.AddField(
            model_name='event',
            name='added_by',
            field=models.ForeignKey(default=729, on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='secretariat.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='secretariat.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Sector'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Trainer'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='cordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Staff'),
        ),
        migrations.AddField(
            model_name='businessclub',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter'),
        ),
        migrations.AddField(
            model_name='businessclub',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member'),
        ),
        migrations.AddField(
            model_name='bcmeeting',
            name='business_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.BusinessClub'),
        ),
    ]
