# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BcMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('secretary', models.CharField(max_length=200)),
                ('guest_speaker', models.CharField(max_length=200)),
                ('minutes', models.TextField()),
                ('next_date', models.DateField(verbose_name='Next Meeting Date')),
                ('cost', models.IntegerField(verbose_name='Cost ($)')),
            ],
            options={
                'verbose_name': 'Business Club Meeting',
                'verbose_name_plural': 'Business Club Meetings',
            },
        ),
        migrations.CreateModel(
            name='BusinessClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('established', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('postal_address', models.CharField(blank=True, max_length=600, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=600, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('established', models.IntegerField()),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=400, null=True)),
                ('account_no', models.IntegerField(blank=True, null=True)),
                ('forex_rate', models.IntegerField()),
                ('mm_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=400)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('t', 'Training'), ('v', 'Company Visit'), ('e', 'Exhibition')], max_length=1, null=True, verbose_name='Event Type')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Full Name')),
                ('join_date', models.DateField(default='2014-01-01')),
                ('subscription_date', models.DateField(blank=True, null=True)),
                ('town', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('business_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.BusinessClub')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='MemberInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Member Interest',
                'verbose_name_plural': 'Member Interests',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100, verbose_name='partner')),
                ('contact', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
                ('speciality', models.ManyToManyField(to='secretariat.MemberInterest')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=300)),
                ('country_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Staffactivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity', models.TextField()),
                ('location', models.CharField(max_length=400)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Staff')),
            ],
            options={
                'verbose_name': 'Staff Activities',
                'verbose_name_plural': 'Staff Activities',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.CharField(max_length=400)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter', verbose_name='Country')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(to='secretariat.MemberInterest'),
        ),
        migrations.AddField(
            model_name='member',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Sector'),
        ),
        migrations.AddField(
            model_name='event',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Staff'),
        ),
        migrations.AddField(
            model_name='event',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='secretariat.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Sector'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Trainer'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='cordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Staff'),
        ),
        migrations.AddField(
            model_name='businessclub',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter'),
        ),
        migrations.AddField(
            model_name='businessclub',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member'),
        ),
        migrations.AddField(
            model_name='bcmeeting',
            name='business_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.BusinessClub'),
        ),
    ]
