# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='created_at',
        ),
    ]
