# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0003_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('1', 'Training'), ('2', 'Company Visit'), ('3', 'Exhibition')], default=1, max_length=1, null=True, verbose_name='Event Type'),
        ),
    ]
