# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0004_auto_20170326_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
