# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0004_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='who_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Profile'),
        ),
    ]
