# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0005_auto_20170326_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
