# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0007_remove_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='who_by',
        ),
    ]
