# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0007_member_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Chapter', verbose_name='Select Country'),
        ),
    ]
