# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0008_auto_20170317_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='account_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='mm_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
