# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0008_auto_20170403_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Joined'),
        ),
    ]
