# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0009_auto_20170318_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='bank_name',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='bank_branch',
            new_name='branch',
        ),
    ]
