# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0010_auto_20170318_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='mm_number',
            field=models.CharField(max_length=50, verbose_name='Mobile Money Number'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='physical_address',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
