# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0011_auto_20170318_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffactivity',
            name='end_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
