# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0012_staffactivity_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffactivity',
            old_name='end_date',
            new_name='activity_end',
        ),
    ]
