# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0013_auto_20170318_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffactivity',
            name='activity_end',
        ),
    ]
