# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0014_remove_staffactivity_activity_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffactivity',
            name='activity_end',
            field=models.DateField(null=True),
        ),
    ]
