# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0016_event_my_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='my_user',
            new_name='user',
        ),
    ]
