# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secretariat', '0022_auto_20170318_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='staffactivity',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
            preserve_default=False,
        ),
    ]
