# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0025_auto_20170318_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')]),
        ),
    ]
