# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0030_auto_20170319_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='sector_desk',
        ),
    ]
