# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0033_auto_20170319_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
