# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0034_remove_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Trainer'),
        ),
    ]
