# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0035_auto_20170319_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default='datetime.datetime.now().today()'),
        ),
    ]
