# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0036_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('t', 'Training'), ('v', 'Company Visit'), ('e', 'Exhibition')], default=1, max_length=1, null=True, verbose_name='Event Type'),
        ),
    ]
