# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0037_auto_20170319_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('t', 'Training'), ('v', 'Company Visit'), ('e', 'Exhibition')], default='t', max_length=1, null=True, verbose_name='Event Type'),
        ),
    ]
