# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0039_auto_20170319_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('10', 'Member'), ('1', 'Non-Member')], default=10, max_length=2),
        ),
    ]
