# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0044_auto_20170319_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('t', 'Training'), ('v', 'Company Visit'), ('e', 'Exhibition')], default='t', max_length=1, null=True, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sub_status',
            field=models.BooleanField(),
        ),
    ]
