# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0045_auto_20170319_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
    ]
