# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0046_auto_20170320_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
