# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0047_chapter_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='account_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='mm_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Money Number'),
        ),
    ]
