# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0048_auto_20170320_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
