# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaika', '0002_auto_20170314_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.AddField(
            model_name='parent',
            name='kid',
            field=models.ManyToManyField(null=True, to='malaika.Child'),
        ),
    ]
