# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretariat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('blog', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('member', models.ForeignKey(default=729, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('token', models.TextField()),
                ('notification_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='secretariat.Member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='secretariat.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notice', models.TextField()),
                ('attachment', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment_type', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('status', models.IntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('member', models.ForeignKey(default=729, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_type', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('status', models.IntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.Notice')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SectorDeskPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_type', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('status', models.IntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('member', models.ForeignKey(default=729, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
                ('sector_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.SectorDesk')),
            ],
        ),
        migrations.CreateModel(
            name='SectorDeskPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_type', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('name', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('status', models.IntegerField(editable=False)),
                ('created_at', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
                ('sector_desk_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.SectorDeskPost')),
            ],
        ),
    ]
