# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0027_auto_20170318_1505'),
        ('mobile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notice', models.TextField()),
                ('attachment', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
