# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0003_auto_20170326_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(upload_to='mobile_app'),
        ),
    ]
