# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_App', '0003_auto_20170318_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='member_id',
            new_name='member',
        ),
    ]
