# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_App', '0008_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2017, 3, 18)),
        ),
    ]
