# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0009_auto_20170318_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
    ]
