# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0010_remove_device_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2017-03-18'),
            preserve_default=False,
        ),
    ]
