# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_App', '0011_device_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
