# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_App', '0012_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
