# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_App', '0020_auto_20170319_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
