# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0021_auto_20170319_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='notification_status',
            field=models.IntegerField(default=1),
        ),
    ]
