# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretariat', '0043_member_sector_desk'),
        ('mobile_app', '0022_auto_20170319_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='secretariat.Member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='secretariat.Member')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterField(
            model_name='sectordeskpost',
            name='attachment_type',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sectordeskpost',
            name='member',
            field=models.ForeignKey(default=729, editable=False, on_delete=django.db.models.deletion.CASCADE, to='secretariat.Member'),
        ),
        migrations.AlterField(
            model_name='sectordeskpost',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sectordeskpost',
            name='sector_desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariat.SectorDesk'),
        ),
        migrations.AlterField(
            model_name='sectordeskpost',
            name='status',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
