# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_App', '0026_auto_20170320_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime.today),
        ),
    ]
