"""
Django settings for aaa project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1p2v$k_ls148_6y7s5wn_*#%ei$2qf*xb6!!_2yglae)-_b3a5'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    'admin_shortcuts',
    'secretariat',
    'mobile_app',    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aaa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'django.template.context_processors.media',

            
            ],
            
        },
    },
]

ADMIN_SHORTCUTS = [
    {
        #'title': '',
        'shortcuts': [
            {
                'url': '/admin/secretariat/member',
                'url_name': '{% url admin:index %}',
                'title': 'Members',
                'count_new': 'aaa.utils.count_members',
                'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'user'
            },
            {
                'url': '/admin/secretariat/bcmeeting',
                'url_name': '{% url admin:index %}',
                'title': 'BC Meetings',
                'count_new': 'aaa.utils.count_meetings',
                'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'notepad'
            },
            {
                'url': '/admin/secretariat/event',
                'url_name': '{% url admin:index %}',
                'title': 'Events',
                'count_new': 'aaa.utils.count_events',
                'count': '30',
                #'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'date',
            },
            {
                'url': '/admin/mobile_app/notice',
                'url_name': '{% url admin:index %}',
                'title': 'Notices',
                'count_new': 'aaa.utils.count_notices',
                'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'flag'
            },
            {
                'url': '/admin/mobile_app/resource',
                'url_name': '{% url admin:index %}',
                'title': 'Resources',
                'count_new': 'aaa.utils.count_resources',
                'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'archive'
            },
            {
                'url': '/admin/mobile_app/sectordeskpost',
                'url_name': '{% url admin:index %}',
                'title': 'Discussions',
                'count_new': 'aaa.utils.count_discussions',
                'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'blog'
            },
            {
                'url': '/admin/mobile_app/feedback',
                'url_name': '{% url admin:index %}',
                'title': 'App Feedback',
                'count_new': 'aaa.utils.count_feedback',
                'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'delivery2'
            },
            {
                'url': '/admin/secretariat/partner',
                'url_name': '{% url admin:index %}',
                'title': 'Partners',
                'count_new': 'aaa.utils.count_partners',
                'has_perms': 'project.utils.has_perms_to_orders',
                'class': 'user',
            },

        ]
    },
]

ADMIN_SHORTCUTS_SETTINGS = {
    'hide_app_list': False,
    'open_new_window': False,
}



# Specifie path to components root (you need to use absolute path)
#BOWER_COMPONENTS_ROOT = os.path.join(PROJECT_ROOT, 'components')



WSGI_APPLICATION = 'aaa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
       #'ENGINE': 'django.db.backends.sqlite3',
       #'NAME': (os.path.join(BASE_DIR, 'db.sqlite3')) ,
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'secretariat',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
        
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'aaa', 'static'),
    #os.path.join(BASE_DIR, "/static/admin/css")
    
)


